### ISSUE TITLE
can not be used by yarn

### ISSUE THREAD

**Issue by forever-z-133** [x-orpheus/svrx-cli#58]
as the title said.

**Comment by dayjoyx** [comment]
We'll support `yarn` very soon

**Comment by dayjoyx** [comment]
@foreverZ133 hi, we've tried with yarn and in fact it works.

Could you please tell us more about your steps to use svrx?

Steps we use:

```bash
yarn global add @svrx/cli
svrx -v
```

![image](https://user-images.githubusercontent.com/8073251/68287092-218e1500-00bd-11ea-9c29-7cf3f58cef2f.png)

**Comment by forever-z-133** [comment]
Thanks, my yarn has some problems, It's OK when I reinstall yarn.
very nice project!!
